name: Patch Font

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'juliamono version'
        required: true
        default: 'v0.054'
        type: string
  repository_dispatch:
    types: [new-release-published]

jobs:
  patch:
    name: "Patch nerdfonts into juliamono"
    runs-on: ubuntu-latest
    env:
      version: ${{ github.event.client_payload.version || inputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: juliamono-nerd-font-variant

      - uses: actions/checkout@v4
        with:
          repository: 'cormullion/juliamono'
          ref: ${{ env.version }}
          path: juliamono

      - name: Patch
        run: |
          mkdir -p font
          docker run --rm -v `pwd`/juliamono:/in -v `pwd`/font/regular:/out nerdfonts/patcher --complete --careful --no-progressbars
          docker run --rm -v `pwd`/juliamono:/in -v `pwd`/font/propo:/out nerdfonts/patcher --complete --variable-width-glyphs --careful --no-progressbars

      - name: Archive Patched Fonts
        uses: actions/upload-artifact@v4
        with:
          name: patched-fonts
          path: font/*
          retention-days: 14

      - name: Zip Release Artifacts
        working-directory: juliamono-nerd-font-variant
        run: |
          zip -j fonts.zip font/*
          zip -j regular.zip font/regular
          zip -j propo.zip font/propo

      - name: Update download link in README.md
        run: |
          cd juliamono-nerd-font-variant
          sed -i 's/releases\/download\/v[0-9.]\+/releases\/download\/${{ env.version }}/g' README.md

      - name: Create file checksum
        id: checksum
        run: |
          for f in *.zip; do
            shasum -a 256 $f > "$f.sha256"
          done
          {
            echo 'sha256_zip<<EOF'
            shasum -a 256 *.zip
            echo EOF
          } >> $GITHUB_OUTPUT

      - uses: actions/create-github-app-token@v1
        id: merge-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v6
        with:
          path: juliamono-nerd-font-variant
          add-paths: README.md
          token: ${{ steps.merge-token.outputs.token }}
          title: "[Merger Bot] Release ${{ env.version }}"
          commit-message: Updated juliamono-nerd-font to ${{ env.version }}
          committer: merger-bot[bot] <131801252+merger-bot[bot]@users.noreply.github.com>
          author: merger-bot[bot] <131801252+merger-bot[bot]@users.noreply.github.com>
          branch: auto-update
          labels: |
            automated pr
            update
          body: |
            Updated juliamono-nerd-font-variant to ${{ env.version }}

      - name: Enable Pull Request auto merge
        if: steps.pr.outputs.pull-request-operation == 'created'
        working-directory: juliamono-nerd-font-variant
        run: gh pr merge --squash --auto "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.merge-token.outputs.token }}

      - uses: actions/create-github-app-token@v1
        if: steps.pr.outputs.pull-request-operation == 'created'
        id: approve-token
        with:
          app-id: ${{ secrets.APP_ID_APPROVE }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_APPROVE }}

      - name: Auto approve
        if: steps.pr.outputs.pull-request-operation == 'created'
        working-directory: juliamono-nerd-font-variant
        run: gh pr review --approve "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.approve-token.outputs.token }}

      - name: Create Release
        if: steps.pr.outputs.pull-request-operation == 'created'
        working-directory: juliamono-nerd-font-variant
        run: gh release create ${{ env.version }} ../fonts.zip ../regular.zip ../propo.zip --generate-notes
        env:
          GH_TOKEN: ${{ steps.merge-token.outputs.token }}
      
      # Old Release File Creation
      # - name: Create Pull Request
      #   id: pr
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ steps.generate-token.outputs.token }}
      #     tag_name: ${{ env.version }}
      #     generate_release_notes: true
      #     append_body: false
      #     files: |
      #       ttf-juliamono-nerd-font-variant-v${{ env.version }}.zip
      #       ttf-juliamono-nerd-font-variant-v${{ env.version }}.tar.gz
      #       juliamono-nerd-font-regular.zip
      #       juliamono-nerd-font-regular.tar.gz
      #       juliamono-nerd-font-propo.zip
      #       juliamono-nerd-font-propo.tar.gz
      #     body: |
      #       `sha -a 256` Checksum
      #       ```bash
      #       ${{ steps.checksum.outputs.sha256_zip }}
      #       ${{ steps.checksum.outputs.sha256_tgz }}
      #       ```
      #       `md5sum` Checksum
      #       ```bash
      #       ${{ steps.checksum.outputs.md5sum_zip }}
      #       ${{ steps.checksum.outputs.md5sum_tgz }}
      #       ```
