name: Patch Font

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'juliamono version'
        required: true
        default: 'v0.054'
        type: string

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: juliamono-nerd-font-variant

      - uses: actions/checkout@v4
        with:
          repository: 'cormullion/juliamono'
          ref: ${{ inputs.version }}
          path: juliamono

      - name: Patch
        run: |
          mkdir -p juliamono-nerd-font-variant/font/{regular,propo}
          docker run --rm -v $(pwd)/juliamono:/in -v $(pwd)/juliamono-nerd-font-variant/font/regular:/out nerdfonts/patcher --complete --careful --no-progressbars
          docker run --rm -v $(pwd)/juliamono:/in -v $(pwd)/juliamono-nerd-font-variant/font/propo:/out nerdfonts/patcher --variable-width-glyphs --complete --careful --no-progressbars
          zip -j "juliamono-nerd-font-regular".zip juliamono-nerd-font-variant/font/regular/*
          tar czf "juliamono-nerd-font-regular".tar.gz juliamono-nerd-font-variant/font/regular/*
          zip -j "juliamono-nerd-font-propo".zip juliamono-nerd-font-variant/font/propo/*
          tar czf "juliamono-nerd-font-propo".tar.gz juliamono-nerd-font-variant/font/propo/*
          zip -j "${{ inputs.version }}".zip juliamono-nerd-font-variant/font/regular/* juliamono-nerd-font-variant/font/propo/*
          tar czf "${{ inputs.version }}".tar.gz juliamono-nerd-font-variant/font/regular/* juliamono-nerd-font-variant/font/propo/* juliamono-nerd-font-variant/font/regular/*
          mkdir -p juliamono-nerd-font-variant/archive
          cp -t juliamono-nerd-font-variant/archive *.tar.gz *.zip

      - name: Commit and Push
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          cd juliamono-nerd-font-variant
          git config --local user.email "131801252+merger-bot[bot]@users.noreply.github.com"
          git config --local user.name "merger-bot[bot]"
          # sed -i "s%\[\*\*Download\*\*\].*%\[\*\*Download\*\*\](https://github.com/${GITHUB_REPOSITORY}/releases/download/${{ inputs.version }}/font.zip)%g" README.md
          git add .
          git commit -m 'Updated juliamono-nerd-font-variant to ${{ inputs.version }}'
          git pull
          git push

      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: "softprops/action-gh-release@v1"
        with:
          token: ${{ steps.generate-token.outputs.token }}
          tag_name: ${{ inputs.version }}
          generate_release_notes: true
          files: |
            ${{ inputs.version }}.zip
            ${{ inputs.version }}.tar.gz
            juliamono-nerd-font-regular.zip
            juliamono-nerd-font-regular.tar.gz
            juliamono-nerd-font-propo.zip
            juliamono-nerd-font-propo.tar.gz

  sha256:
    runs-on: ubuntu-latest
    needs: patch
    steps:
      - name: generate-sha
        id: generate-sha
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ github.repository }}
          VERSION: ${{ inputs.version }}
        run: gh workflow run release_sha.yml --repo $GH_REPO --ref main -f version=$VERSION
