name: Patch Font

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'juliamono version'
        required: true
        default: 'v0.054'
        type: string
  repository_dispatch:
    types: [new-release-published]

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-latest
    env:
      version: ${{ github.event.client_payload.version || inputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: juliamono-nerd-font-variant

      - uses: actions/checkout@v4
        with:
          repository: 'cormullion/juliamono'
          ref: ${{ env.version }}
          path: juliamono

      - name: Patch
        run: |
          mkdir -p juliamono-nerd-font-variant/font/{regular,propo}
          docker run --rm -v $(pwd)/juliamono:/in -v $(pwd)/juliamono-nerd-font-variant/font/regular:/out nerdfonts/patcher --complete --careful --no-progressbars
          docker run --rm -v $(pwd)/juliamono:/in -v $(pwd)/juliamono-nerd-font-variant/font/propo:/out nerdfonts/patcher --variable-width-glyphs --complete --careful --no-progressbars
          zip -j "juliamono-nerd-font-regular".zip juliamono-nerd-font-variant/font/regular/*
          tar czf "juliamono-nerd-font-regular".tar.gz juliamono-nerd-font-variant/font/regular/*
          zip -j "juliamono-nerd-font-propo".zip juliamono-nerd-font-variant/font/propo/*
          tar czf "juliamono-nerd-font-propo".tar.gz juliamono-nerd-font-variant/font/propo/*
          zip -j "${{ env.version }}".zip juliamono-nerd-font-variant/font/regular/* juliamono-nerd-font-variant/font/propo/*
          tar czf "${{ env.version }}".tar.gz juliamono-nerd-font-variant/font/regular/* juliamono-nerd-font-variant/font/propo/*
          mkdir -p juliamono-nerd-font-variant/archive
          cp -t juliamono-nerd-font-variant/archive *.tar.gz *.zip

      - name: Commit and Push
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          cd juliamono-nerd-font-variant
          git config --local user.email "131801252+merger-bot[bot]@users.noreply.github.com"
          git config --local user.name "merger-bot[bot]"
          # sed -i "s%\[\*\*Download\*\*\].*%\[\*\*Download\*\*\](https://github.com/${GITHUB_REPOSITORY}/releases/download/${{ env.version }}/font.zip)%g" README.md
          git add .
          git commit -m 'Updated juliamono-nerd-font-variant to ${{ env.version }}'
          git push

      - name: checksum
        id: checksum
        run: |
          cd juliamono-nerd-font-variation/archive
          {
            echo 'sha256_zip<<EOF'
            shasum -a 256 *.zip
            echo EOF
          } >> $GITHUB_OUTPUT
          {
            echo 'sha256_tgz<<EOF'
            shasum -a 256 *.tar.gz
            echo EOF
          } >> $GITHUB_OUTPUT
          {
            echo 'md5sum_zip<<EOF'
            md5sum *.zip
            echo EOF
          } >> $GITHUB_OUTPUT
          {
            echo 'md5sum_tgz<<EOF'
            md5sum *.tar.gz
            echo EOF
          } >> $GITHUB_OUTPUT

      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: "softprops/action-gh-release@v1"
        with:
          token: ${{ steps.generate-token.outputs.token }}
          tag_name: ${{ env.version }}
          generate_release_notes: true
          append_body: false
          files: |
            ttf-juliamono-nerd-font-variant-v${{ env.version }}.zip
            ttf-juliamono-nerd-font-variant-v${{ env.version }}.tar.gz
            juliamono-nerd-font-regular.zip
            juliamono-nerd-font-regular.tar.gz
            juliamono-nerd-font-propo.zip
            juliamono-nerd-font-propo.tar.gz
          body: |
            `sha -a 256` Checksum
            ```bash
            ${{ steps.checksum.outputs.sha256_zip }}

            ${{ steps.checksum.outputs.sha256_tgz }}
            ```
            `md5sum` Checksum
            ```bash
            ${{ steps.checksum.outputs.md5sum_zip }}

            ${{ steps.checksum.outputs.md5sum_tgz }}
            ```
