name: Patch Font

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'juliamono version'
        required: true
        default: 'v0.050'
        type: string

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: juliamono-nerd-font
        
      - uses: actions/checkout@v3
        with:
          repository: 'cormullion/juliamono'
          ref: ${{ inputs.version }}
          path: juliamono
          
      - name: Patch
        run: |
          docker run --rm -v `pwd`/juliamono:/in -v `pwd`/juliamono-nerd-font:/out nerdfonts/patcher --mono --complete --careful --no-progressbars 
          
      - name: Commit and Push
        run: |
          cd juliamono-nerd-font
          git add .
          git commit -m 'Updated juliamono-nerd-font to ${{ inputs.version }}'
          git push
